version: "2.1"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "mabu"
      MYSQL_PASSWORD: "123456"

  slotgameserver:
    image: slotgameserver:latest
    build: .
    environment:
      NODE_ENV: development
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      MYSQL_HOST: "mysql"
      MYSQL_PORT: 3306
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"

    ports:
      - 8000:8000
      - 8080:8080
    depends_on:
      - redis
      - mysql
    links:
      - redis
      - mysql
    # command: npm start
    # command: sh
